on: [push]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    name: Build Docker image to run tests for ros_messaging
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: ./